services:
  frontend:
    build:
      context: ./LGC.Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./LGC.Frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build:
      context: .
      dockerfile: LGC.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__Postgres=Host=db;Database=postgres;Port=5432;Username=postgres;Password=postgres

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
